/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scm_jnidemon_JniKet */

#ifndef _Included_com_scm_jnidemon_JniKet
#define _Included_com_scm_jnidemon_JniKet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scm_jnidemon_JniKet
 * Method:    testJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_scm_jnidemon_JniKet_testJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
